ark.api.url=https://ark.cn-beijing.volces.com/api/v3/responses
ark.upload.url=https://ark.cn-beijing.volces.com/api/v3/files
ark.model=doubao-seed-2-0-lite-260215
ark.api.key=ark-751bf22e-e8d4-4941-983f-f814ca1e2e55-c3e19
